### PR TITLE
add "charset=utf-8" to Content-Type

### PR DESCRIPTION
**Pull request by xland**
add "charset=utf-8" to Content-Type

### CODE REVIEW

**Comment by dom96** [comment]
Why should this be the default for everything? For most things it just adds noise.

**Comment by xland** [comment]
Because with out that setting, Chinese words do not display correctly.
I think Japanese, Korean  are  as same as Chinese.
And I think it is better  jester sets that for programmer.
Thank you.

**Comment by xland** [comment]
Please,Test that.
It is really a problem for CJK users!
@dom96

**Comment by dom96** [comment]
Alright. I shall merge it.

**Comment by xland** [comment]
Thank you

**Pull request merged**
