### PR TITLE
partially fix #160 (related to nilseq); `nimble test` still fails after a bit

### LINKED ISSUE #160: `nimble test` fails
/cc @dom96 

from a fresh clone, and using nim HEAD:

  Verifying dependencies for asynctools@0.1.0
  Compiling tests/alltest.nim (from package jester) using c backend
/private/tmp/d50/jester/tests/alltest.nim(3, 1) template/generic instantiation from here
/private/tmp/d50/jester/jester.nim(9, 1) template/generic instantiation from here
/private/tmp/d50/jester/jester/request.nim(80, 1) template/generic instantiation from here
/private/tmp/d50/jester/jester/request.nim(101, 7) Warning: use stdlib; parseUrlQuery is deprecated [Deprecated]
        parseUrlQuery(req.body, result)
        ^
/private/tmp/d50/jester/tests/alltest.nim(3, 1) template/generic instantiation from here
/private/tmp/d50/jester/jester.nim(80, 1) template/generic instantiation from here
/private/tmp/d50/jester/jester.nim(82, 14) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim/lib/system.nim(408, 10) Error: type mismatch: got <RawHeaders, nil>
but expected one of:

expression: headers == nil
    not (x == y)
           ^
       Tip: 13 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 256
        ... Command: "/Users/timothee/.nimble//bin/nim" c --noNimblePath --path:"/Users/timothee/.nimble/pkgs/httpbeast-0.2.1" --path:"/Users/timothee/.nimble/pkgs/asynctools-0.1.0" --path:"/Users/timothee/.nimble/pkgs/asynctools-0.1.0" "--hints:off"  "tests/alltest.nim"
Traceback (most recent call last)
/private/tmp/d50/jester/tests/tester.nim(205) tester
/Users/timothee/.nimble/pkgs/asynctools-0.1.0/asynctools/asyncproc.nim(216) processID
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: './tests/tester '
       Tip: 13 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 256
        ... Command: "/Users/timothee/.nimble//bin/nim" c --noNimblePath --path:"/Users/timothee/.nimble/pkgs/httpbeast-0.2.1" --path:"/Users/timothee/.nimble/pkgs/asynctools-0.1.0" --path:"/Users/timothee/.nimble/pkgs/asynctools-0.1.0" "-r"  "tests/tester"
stack trace: (most recent call last)
private/tmp/d50/jester/jester.nimble(22) testTask
Users/timothee/git_clone/nim/Nim/lib/system/nimscript.nim(237) exec
/Users/timothee/git_clone/nim/Nim/lib/system/nimscript.nim(237, 7) Error: unhandled exception: FAILED: nimble c -y -r tests/tester

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @dom96 
could we please merge this and fix remaining bugs later? at least now a project that depends on jester can compile
unless you have a quick fix in mind to fix remaining bugs

see logs below for remaining errors

### CODE REVIEW

**Comment by timotheecour** [comment]
```
  Executing task test in /Users/timothee/git_clone/nim/jester/jester.nimble
  Verifying dependencies for jester@0.4.0
   Warning: No nimblemeta.json file found in /Users/timothee/.nimble/pkgs/choosenim-0.3.2
      Info: Dependency on httpbeast@>= 0.2.0 already satisfied
  Verifying dependencies for httpbeast@0.2.1
      Info: Dependency on asynctools@any version already satisfied
  Verifying dependencies for asynctools@0.1.0
      Info: Dependency on asynctools@any version already satisfied
  Verifying dependencies for asynctools@0.1.0
  Compiling tests/tester (from package jester) using c backend
  Verifying dependencies for jester@0.4.0
   Warning: No nimblemeta.json file found in /Users/timothee/.nimble/pkgs/choosenim-0.3.2
      Info: Dependency on httpbeast@>= 0.2.0 already satisfied
  Verifying dependencies for httpbeast@0.2.1
      Info: Dependency on asynctools@any version already satisfied
  Verifying dependencies for asynctools@0.1.0
      Info: Dependency on asynctools@any version already satisfied
  Verifying dependencies for asynctools@0.1.0
  Compiling tests/alltest.nim (from package jester) using c backend
   Success: Execution finished
[34mGetting http://localhost:5454[0m
Connection refused
Async traceback:
  /Users/timothee/git_clone/nim/jester/tests/tester.nim(197)         tester
  /Users/timothee/git_clone/nim/jester/tests/tester.nim(61)          allTest
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1645) waitFor
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183)  processPendingCallbacks
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(36)      dial_continue
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncnet.nim(263)       dialIter
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncfutures.nim(302)   read
  #[
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(197)         tester
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(61)          allTest
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1645) waitFor
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183)  processPendingCallbacks
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(36)      newConnection_continue
    /Users/timothee/git_clone/nim/Nim/lib/pure/httpclient.nim(1111)    newConnectionIter
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncfutures.nim(302)   read
  ]#
  #[
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(197)         tester
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(61)          allTest
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1645) waitFor
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183)  processPendingCallbacks
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(36)      requestAux_continue
    /Users/timothee/git_clone/nim/Nim/lib/pure/httpclient.nim(1173)    requestAuxIter
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncfutures.nim(302)   read
  ]#
  #[
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(197)         tester
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(61)          allTest
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1645) waitFor
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183)  processPendingCallbacks
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(36)      request_continue
    /Users/timothee/git_clone/nim/Nim/lib/pure/httpclient.nim(1204)    requestIter
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncfutures.nim(302)   read
  ]#
  #[
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(197)         tester
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(61)          allTest
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1645) waitFor
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183)  processPendingCallbacks
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(36)      request_continue
    /Users/timothee/git_clone/nim/Nim/lib/pure/httpclient.nim(1227)    requestIter
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncfutures.nim(302)   read
  ]#
Exception message: Connection refused
Exception type:
[34mProcess: [0mINFO Jester is making jokes at http://127.0.0.1:5454/foo
Starting 1 threads[0m
[34mGetting http://localhost:5454[0m
[34mProcess: [0mERROR /Users/timothee/git_clone/nim/jester/tests/alltest.nim(29) alltest
/Users/timothee/git_clone/nim/jester/jester.nim(471) serve
/Users/timothee/.nimble/pkgs/httpbeast-0.2.1/httpbeast.nim(414) run
/Users/timothee/.nimble/pkgs/httpbeast-0.2.1/httpbeast.n[0m
[34mProcess: [0mim(287) eventLoop
/Users/timothee/.nimble/pkgs/httpbeast-0.2.1/httpbeast.nim(219) processEvents
/Users/timothee/git_clone/nim/jester/jester.nim(470) :anonymous
/Users/timothee/git_clone/nim/jester/jester.nim(365) handleRequest
/Users/timothee/git_clone/nim[0m
[34mProcess: [0m/jester/jester/request.nim(158) pathInfo
/Users/timothee/git_clone/nim/jester/jester/request.nim(152) stripAppName
Expected script name at beginning of path. Got path: / script name: /foo[0m
[32mServer started![0m
[34mProcess: [0mDEBUG   502 Bad Gateway {"content-type": @["text/html;charset=utf-8"]}
ERROR /Users/timothee/git_clone/nim/jester/tests/alltest.nim(29) alltest
/Users/timothee/git_clone/nim/jester/jester.nim(471) serve
/Users/timothee/.nimble/pkgs/httpbeast-0.2.1/httpbeas[0m
[34mProcess: [0mt.nim(414) run
/Users/timothee/.nimble/pkgs/httpbeast-0.2.1/httpbeast.nim(287) eventLoop
/Users/timothee/.nimble/pkgs/httpbeast-0.2.1/httpbeast.nim(219) processEvents
/Users/timothee/git_clone/nim/jester/jester.nim(470) :anonymous
/Users/timothee/git_clone[0m
[34mProcess: [0m/nim/jester/jester.nim(365) handleRequest
/Users/timothee/git_clone/nim/jester/jester/request.nim(158) pathInfo
/Users/timothee/git_clone/nim/jester/jester/request.nim(152) stripAppName
Expected script name at beginning of path. Got path: / script name: /f[0m
[34mProcess: [0moo[0m
[OK] doesn't crash on missing script name
[OK] can access root
[OK] /nil
[OK] /halt
[OK] /guess
[OK] /redirect
[OK] regex
[OK] resp
[OK] template
[OK] json
[OK] sendFile
[OK] can access query

[Suite] static
  [OK] index.html
  [OK] test_file.txt
  [OK] detects attempts to read parent dirs

[Suite] extends
  [OK] simple
  [OK] params
  [OK] separate module
  [OK] external regex
  [OK] regex path prefix escaped

[Suite] error
  [OK] exception
  [OK] HttpCode handling
  [OK] `pass` in error handler
  [OK] custom 404

[Suite] before/after
  [OK] before - halt
  [OK] before - unaffected
  [OK] before - global
  [OK] before - 404
  [OK] after - added
  Verifying dependencies for jester@0.4.0
   Warning: No nimblemeta.json file found in /Users/timothee/.nimble/pkgs/choosenim-0.3.2
      Info: Dependency on httpbeast@>= 0.2.0 already satisfied
  Verifying dependencies for httpbeast@0.2.1
      Info: Dependency on asynctools@any version already satisfied
  Verifying dependencies for asynctools@0.1.0
      Info: Dependency on asynctools@any version already satisfied
  Verifying dependencies for asynctools@0.1.0
  Compiling tests/alltest.nim (from package jester) using c backend
   Success: Execution finished
[34mGetting http://localhost:5454[0m
[34mProcess: [0m[0m
[31mProcess terminated[0m
Connection refused
Async traceback:
  /Users/timothee/git_clone/nim/jester/tests/tester.nim(198)         tester
  /Users/timothee/git_clone/nim/jester/tests/tester.nim(61)          allTest
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1645) waitFor
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183)  processPendingCallbacks
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(36)      dial_continue
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncnet.nim(263)       dialIter
  /Users/timothee/git_clone/nim/Nim/lib/pure/asyncfutures.nim(302)   read
  #[
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(198)         tester
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(61)          allTest
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1645) waitFor
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183)  processPendingCallbacks
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(36)      newConnection_continue
    /Users/timothee/git_clone/nim/Nim/lib/pure/httpclient.nim(1111)    newConnectionIter
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncfutures.nim(302)   read
  ]#
  #[
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(198)         tester
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(61)          allTest
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1645) waitFor
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183)  processPendingCallbacks
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(36)      requestAux_continue
    /Users/timothee/git_clone/nim/Nim/lib/pure/httpclient.nim(1173)    requestAuxIter
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncfutures.nim(302)   read
  ]#
  #[
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(198)         tester
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(61)          allTest
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1645) waitFor
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183)  processPendingCallbacks
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(36)      request_continue
    /Users/timothee/git_clone/nim/Nim/lib/pure/httpclient.nim(1204)    requestIter
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncfutures.nim(302)   read
  ]#
  #[
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(198)         tester
    /Users/timothee/git_clone/nim/jester/tests/tester.nim(61)          allTest
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1645) waitFor
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183)  processPendingCallbacks
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(36)      request_continue
    /Users/timothee/git_clone/nim/Nim/lib/pure/httpclient.nim(1227)    requestIter
    /Users/timothee/git_clone/nim/Nim/lib/pure/asyncfutures.nim(302)   read
  ]#
Exception message: Connection refused
Exception type:
[34mGetting http://localhost:5454[0m
[34mProcess: [0mINFO Jester is making jokes at http://127.0.0.1:5454/foo
ERROR /Users/timothee/git_clone/nim/jester/tests/alltest.nim(29) alltest
/Users/timothee/git_clone/nim/jester/jester.nim(484) serve
/Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1640)[0m
[34mProcess: [0mrunForever
/Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
/Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
/Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183) processPendingCallbacks
/Users/t[0m
[34mProcess: [0mimothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(39) processRequest_continue
/Users/timothee/git_clone/nim/Nim/lib/pure/asynchttpserver.nim(259) processRequestIter
/Users/timothee/git_clone/nim/jester/jester.nim(478) :anonymous
/Users/timothee/git_clone/n[0m
[34mProcess: [0mim/jester/jester.nim(365) handleRequest
/Users/timothee/git_clone/nim/jester/jester/request.nim(158) pathInfo
/Users/timothee/git_clone/nim/jester/jester/request.nim(152) stripAppName
Expected script name at beginning of path. Got path: / script name: /foo[0m
[34mProcess: [0m[0m
[32mServer started![0m
[34mProcess: [0mDEBUG   502 Bad Gateway {"content-type": @["text/html;charset=utf-8"]}
ERROR /Users/timothee/git_clone/nim/jester/tests/alltest.nim(29) alltest
/Users/timothee/git_clone/nim/jester/jester.nim(484) serve
/Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispa[0m
[34mProcess: [0mtch.nim(1640) runForever
/Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1509) poll
/Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(1275) runOnce
/Users/timothee/git_clone/nim/Nim/lib/pure/asyncdispatch.nim(183) processPendingCall[0m
[34mProcess: [0mbacks
/Users/timothee/git_clone/nim/Nim/lib/pure/asyncmacro.nim(39) processRequest_continue
/Users/timothee/git_clone/nim/Nim/lib/pure/asynchttpserver.nim(259) processRequestIter
/Users/timothee/git_clone/nim/jester/jester.nim(478) :anonymous
/Users/timoth[0m
[34mProcess: [0mee/git_clone/nim/jester/jester.nim(365) handleRequest
/Users/timothee/git_clone/nim/jester/jester/request.nim(158) pathInfo
/Users/timothee/git_clone/nim/jester/jester/request.nim(152) stripAppName
Expected script name at beginning of path. Got path: / scr[0m
[34mProcess: [0mipt name: /foo[0m
[OK] doesn't crash on missing script name
[OK] can access root
[OK] /nil
[OK] /halt
[OK] /guess
[OK] /redirect
[OK] regex
[OK] resp
[OK] template
[OK] json
[OK] sendFile
[OK] can access query

[Suite] static
  [OK] index.html
  [OK] test_file.txt
  [OK] detects attempts to read parent dirs

[Suite] extends
  [OK] simple
  [OK] params
  [OK] separate module
  [OK] external regex
  [OK] regex path prefix escaped

[Suite] error
  [OK] exception
  [OK] HttpCode handling
  [OK] `pass` in error handler
  [OK] custom 404

[Suite] before/after
  [OK] before - halt
  [OK] before - unaffected
  [OK] before - global
  [OK] before - 404
  [OK] after - added
Error: unhandled exception: No such file or directory [OSError]
/Users/timothee/git_clone/nim/jester/tests/tester.nim(203, 46): Check failed: execCmd("nim c --path:. " & path) == QuitSuccess
execCmd("nim c --path:. " & path) was 256
QuitSuccess was 0
[FAILED] Nim in Action - Tweeter
       Tip: 13 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 256
        ... Command: "/Users/timothee/.nimble//bin/nim" c --noNimblePath --path:"/Users/timothee/.nimble/pkgs/httpbeast-0.2.1" --path:"/Users/timothee/.nimble/pkgs/asynctools-0.1.0" --path:"/Users/timothee/.nimble/pkgs/asynctools-0.1.0" "-r"  "tests/tester"
```

**Comment by dom96** [comment]
You need to ``git submodule init``

**Comment by dom96** [comment]
Fixed differently.

**Comment by timotheecour** [comment]
> git submodule init

still fails after that with similar (or same) error msg as shown above; I'm on OSX

**Comment by timotheecour** [comment]
@tim-st could you create a new issue for that to avoid it getting lost?

**Pull request closed without merging**
