### PR TITLE
requires "asynctools" now that asynctools was updated

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @dom96 
refs https://github.com/nim-lang/RFCs/issues/393#issue-931023120
refs https://github.com/cheatfate/asynctools/pull/28

### CODE REVIEW

**Comment by dom96** [comment]
Thanks, will merge as soon as I fix Jester's CI.

**Comment by timotheecour** [comment]
> Thanks, will merge as soon as I fix Jester's CI.

how about github actions now that travis chaned their pricing plans and that most projects migrate away from travis?

**Comment by dom96** [comment]
Of course, that is my plan

**Comment by dom96** [comment]
Done via https://github.com/dom96/jester/commit/3cd2eb5bf77c37e7d7dbc51c0268a0156bd48e34

**Pull request closed without merging**
