### PR TITLE
Log "0.0.0.0" as default IP address #93

### PR DESCRIPTION
**Pull request by FedericoCeratto**

### CODE REVIEW

**Comment by dom96** [comment]
Can I copy and paste this IP address into my browser just like I can with the ``localhost`` address?

**Comment by FedericoCeratto** [comment]
It work on Linux, not sure about other OSes.

**Comment by Araq** [comment]
Doesn't work on Windows 10. I doubt it works on other Windows versions.

**Comment by dom96** [comment]
Reverted.

**Pull request merged**
