### PR TITLE
Allow using both setHeader and resp w/ headers

### PR DESCRIPTION
**Pull request by iffy**
Currently making a request of a handler like this will only include the `Content-Type` header. This change makes it so that the `foo` and `bar` headers are added to the response as well.

```nim
  get "/manyheaders":
    setHeader(responseHeaders, "foo", "foo")
    setHeader(responseHeaders, "bar", "bar")
    resp Http200, {"Content-Type": "text/plain"}, "result"
```

### CODE REVIEW

**Comment by iffy** [comment]
Oops; this includes the code from https://github.com/dom96/jester/pull/267 as well. I can remake this PR if you'd like.

**Comment by dom96** [comment]
Yeah, please split it if you can.

**Comment by dom96** [comment]
Any news on this? :)

**Comment by dom96** [comment]
Friendly ping

**Comment by iffy** [comment]
I've submitted #300 to do the minimal change.

**Pull request closed without merging**
