### PR TITLE
Preserve MultipartData order

### LINKED ISSUE #78: Preserve order in multipart requests
Right now multipart data is read into a `Table` using `content-disposition`'s `name` field as key, which means that the order of parts is lost, and parts with overlapping names (or without `name` field in `content-disposition` header) collide. The easiest solution is to make `MultipartData` use `OrderedTable` instead - this way most existing code should work as intended, but restoring initial part order is made possible.

### PR DESCRIPTION
**Pull request by nigredo-tori**
closes #78

### CODE REVIEW

**Comment by dom96** [comment]
In #78 you described another problem related to collisions (between header names?), will this still remain a problem after this PR?

**Comment by dom96** [comment]
Thanks for the PRs btw! :)

**Comment by nigredo-tori** [comment]
> will this still remain a problem after this PR? 

It should not - OrderedTable allows storing multiple values for the same key, so iterating over pairs will return all the added values, regardless of whether their keys overlap. That's why I've changed 
```nim
result[name] = newPart
```
to
```nim
result.add(name, newPart)
```

**Comment by dom96** [comment]
@nigredo-tori awesome. I didn't know that :)

**Pull request merged**
