### PR TITLE
fix deprecated stuff

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

**Comment by dom96** [comment]
`:typed` as a template return type is deprecated now? Since when and why?

**Comment by narimiran** [comment]
I don't know since when exactly, but it has been like that for a quite some time now. And there are others who could better answer your `why?` question.

Either way, I don't see why would that stop you from merging this, but if you insist I can make a PR without those changes.

**Comment by dom96** [comment]
Happy to merge, but can you run ``nimble test`` and ensure everything still passes?

**Comment by narimiran** [comment]
This is what I get with the `master` branch of `jester`:

```
/home/miran/.nimble/pkgs/asynctools-#pr_fix_compilation/asynctools/asyncsync.nim(159, 15) Error: type mismatch: got <proc (){.closure.}>
but expected one of:
proc callSoon(cbproc: proc () {.gcsafe.})
  first type mismatch at position: 1
  required type for cbproc: proc (){.closure, gcsafe.}
  but expression 'wakeupAll' is of type: proc (){.closure.}
  This expression is not GC-safe. Annotate the proc with {.gcsafe.} to get extended error information.

expression: callSoon(wakeupAll)
       Tip: 6 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: "/home/miran/code/nim-lang/Nim/bin/nim" c --noNimblePath -d:NimblePkgVersion=0.4.3 --path:"/home/miran/.nimble/pkgs/httpbeast-0.2.2" --path:"/home/miran/.nimble/pkgs/asynctools-#pr_fix_compilati
on" --path:"/home/miran/.nimble/pkgs/asynctools-#pr_fix_compilation" "-r"  "tests/tester"
stack trace: (most recent call last)
/tmp/nimblecache/nimscriptapi.nim(165, 16)
/home/miran/code/nim/packages/jester/jester_63074.nims(27, 8) testTask
/home/miran/code/nim-lang/Nim/lib/system/nimscript.nim(260, 7) exec
/home/miran/code/nim-lang/Nim/lib/system/nimscript.nim(260, 7) Error: unhandled exception: FAILED: nimble c -y -r tests/tester [OSError]
     Error: Exception raised during nimble script execution
```

No idea what's going on there, but you might want to check it on your machine.
(The same thing happens with this PR, if that's some consolation)

**Comment by iffy** [comment]
I'm getting the same error @narimiran posted above.  Shall I open a new issue?

**Comment by dom96** [comment]
Would be nice if you could fix it :)

**Comment by iffy** [comment]
:) It'll be fixed with https://github.com/dom96/jester/pull/263 (Here's the fix: https://github.com/cheatfate/asynctools/pull/28/commits/143b636ec429a42dd1d64af90695ceca1214afe5)

**Pull request merged**
